version: "3"
services:
  livestream:
    image: ghcr.io/sb-im/sphinx:debug-amd64
    container_name: livestream
    command:
      - --debug
      - livestream
      - -c
      - /config/config.toml
    ports:
      - "5004:5004/udp"
      - "5005:5005/udp"
    volumes:
      - ../../sphinx/config/config.docker.toml:/config/config.toml:ro
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - mosquitto
      - broadcast
      - turn
      - loki
    restart: always
    logging: &loki
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"
        loki-retries: "5"
        loki-batch-size: "400"

  broadcast:
    image: ghcr.io/sb-im/skywalker:debug
    container_name: broadcast
    command:
      - --debug
      - broadcast
      - -c
      - /config/config.toml
    ports:
      - "8080:8080"
    volumes:
      - ../config/config.docker.toml:/config/config.toml:ro
    depends_on:
      - mosquitto
      - turn
      - loki
    restart: always
    logging: *loki

  turn:
    image: ghcr.io/sb-im/skywalker:debug
    container_name: turn
    command:
      - --debug
      - turn
      - -c
      - /config/config.toml
    network_mode: host
    volumes:
      - ../config/config.docker.toml:/config/config.toml:ro
    depends_on:
      - loki
    restart: always
    logging: *loki

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ../config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    depends_on:
      - loki
    restart: always
    logging: *loki

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging: *loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    restart: always
    logging: *loki
