# MQTT client config
mqtt-server: tcp://mosquitto:1883
mqtt-clientID: mqtt_edge
mqtt-username: user
mqtt-password: password

# MQTT client config for webRTC signaling
topic-offer: /edge/livestream/signal/offer
topic-answer-suffix: /edge/livestream/signal/answer
# topic-candidate-send is opposite to edge's topic-candidate-recv-suffix topic
topic-candidate-send-suffix: /edge/livestream/signal/candidate/recv
# topic-candidate-recv-suffix is opposite to edge's topic-candidate-send-suffix topic
topic-candidate-recv-suffix: /edge/livestream/signal/candidate/send
qos: 0
retained: false

# WebRTC config
ice-server: stun:stun.l.google.com:19302
ice-server-username: ""
ice-server-credential: ""
enable-frontend: false

# Signal server config
host: 0.0.0.0
port: 8080
