[mqtt]
client_id = "mqtt_cloud"
password = "password"
server = "tcp://mosquitto:1883"
username = "user"

[mqtt_client]
topic_answer_prefix = "/edge/livestream/signal/answer"
topic_offer = "/edge/livestream/signal/offer"

# topic_candidate_send is opposite to edge's topic_candidate_recv_prefix topic
topic_candidate_send_prefix = "/edge/livestream/signal/candidate/recv"
# topic_candidate_recv_prefix is opposite to edge's topic_candidate_send_prefix topic
topic_candidate_recv_prefix = "/edge/livestream/signal/candidate/send"

qos = 0
retained = false

[webrtc]
enable_frontend = false

ice_server = "turn:example.com:3478"
ice_server_credential = "password"
ice_server_username = "user"

[signal_server]
host = "0.0.0.0"
port = 8080

[turn]
port = 3478
public_ip = "127.0.0.1"
realm = "example.com"
relay_max_port = 55000
relay_min_port = 50000
username = "user"
password = "password"
