[mqtt]
client_id = "mqtt_cloud"
username = "user"
password = "password"
server = "tcp://mosquitto:1883"

[mqtt_client]
topic_offer_prefix = "/edge/livestream/signal/offer"
topic_answer_prefix = "/edge/livestream/signal/answer"

# topic_candidate_send is opposite to edge's topic_candidate_recv_prefix topic
topic_candidate_send_prefix = "/edge/livestream/signal/candidate/recv"
# topic_candidate_recv_prefix is opposite to edge's topic_candidate_send_prefix topic
topic_candidate_recv_prefix = "/edge/livestream/signal/candidate/send"

topic_hook_stream_prefix = "/edge/livestream/hook"

qos = 0
retained = false

[webrtc]
enable_frontend = false

ice_server = "turn:example.com:3478"
ice_server_username = "user"
ice_server_credential = "password"

[signal_server]
host = "0.0.0.0"
port = 8080

[turn]
port = 3478
public_ip = "127.0.0.1"
realm = "example.com"
relay_min_port = 50000
relay_max_port = 55000
username = "user"
password = "password"
